[tools]
aqua = "latest"
gcloud = "latest"
awscli = "latest"
jq = "latest"
yq = "latest"
uv = "latest"
"npm:takt" = "latest"
"npm:playwright-cli" = "latest"
cloud-sql-proxy = "2.21.0"
go = "1.26.0"
node = "22"
yarn = "1.22.22"
